export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SELF_SUCCESS = "SELF_SUCCESS";
export const SELF_FAILED = "SELF_FAILED";
export const WEATHER_SUCCESS = "WEATHER_SUCCESS";
export const QUOTE_SUCCESS = "QUOTE_SUCCESS";
export const SELF_PLANET_SUCCESS = "SELF_PLANET_SUCCESS";
export const SELF_ZODIAC_SUCCESS = "SELF_ZODIAC_SUCCESS";
export const SELF_HOUSE_SUCCESS = "SELF_HOUSE_SUCCESS";